# conda env create --file environment.yml
name: pandas_numpy_prediction_houses_colombia
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - matplotlib==3.7.1
  - pandas==1.5.3
  - numpy==1.23.5
  - seaborn==0.12.2
  - pip
  - pyprojroot
  - python=3.10.12
  - pip:
    - pyhere
    